### ISSUE TITLE
refactor and release v1.0.0

### ISSUE THREAD

**Issue by hiroppy** [hiroppy/fusuma#56]
## TODO

- [x] update some dependencies (such as react, etc...)
- [x] modify performance
- [x] drop bespoke? (because bespoke use `window` so we cannot use 2 slides on same window)
- [ ] add an embeded field
- [ ] modify presentation host ui

**Comment by hiroppy** [comment]
https://github.com/webslides/webslides/

**Comment by hiroppy** [comment]
https://github.com/hiroppy/fusuma/pull/60
